import React, { useState } from 'react';
import { Bot, Sparkles, Zap, ArrowRight, Loader2, AlertCircle, HelpCircle } from 'lucide-react';
import { QuizPack, Difficulty } from '../types';

interface AiQuizGeneratorProps {
  onStartQuiz: (quizPack: QuizPack) => void;
  primaryColor: string;
}

const QUICK_TOPICS = [
  '80s Synthwave & Rock',
  'Quantum Computing',
  'Marvel Cinematic Universe',
  'Ancient Mythology',
  'Artificial Intelligence & Robotics',
  'World Food & Gastronomy',
  'Space Exploration & NASA',
  'Video Game History',
];

export const AiQuizGenerator: React.FC<AiQuizGeneratorProps> = ({ onStartQuiz, primaryColor }) => {
  const [topicInput, setTopicInput] = useState('');
  const [difficulty, setDifficulty] = useState<Difficulty>('Medium');
  const [questionCount, setQuestionCount] = useState<number>(5);
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleGenerateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topicInput.trim()) return;

    setIsGenerating(true);
    setErrorMsg(null);

    try {
      const response = await fetch('/api/generate-quiz', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topicInput.trim(),
          difficulty,
          questionCount,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || 'Failed to generate AI quiz.');
      }

      const generatedQuiz: QuizPack = {
        id: `ai-${Date.now()}`,
        title: data.quiz.title || `AI Quiz: ${topicInput}`,
        category: data.quiz.category || 'AI Custom',
        description: data.quiz.description || `Custom trivia generated by Gemini AI on ${topicInput}`,
        iconName: 'Sparkles',
        difficulty,
        estimatedMinutes: Math.round(questionCount * 0.6),
        questions: data.quiz.questions.map((q: any, idx: number) => ({
          id: `ai-q-${idx}`,
          question: q.question,
          options: q.options,
          correctIndex: q.correctIndex,
          explanation: q.explanation,
          category: data.quiz.category || 'AI Custom',
          difficulty,
        })),
        isAiGenerated: true,
      };

      onStartQuiz(generatedQuiz);
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || 'Error generating quiz. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 animate-fadeIn" id="ai-quiz-generator-container">
      {/* Banner */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-pink-500/10 text-pink-600 dark:text-pink-400 font-extrabold text-xs uppercase tracking-wider mb-4 border border-pink-500/20">
          <Bot className="w-4 h-4" /> Powered by Gemini AI
        </div>
        <h1 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white mb-2">
          AI Custom Quiz Generator
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
          Type ANY custom topic under the sun, and Gemini AI will instantly craft a 30s challenge quiz for you!
        </p>
      </div>

      {/* Main Generator Card */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 sm:p-8 border border-slate-200/80 dark:border-slate-800 shadow-xl mb-8">
        <form onSubmit={handleGenerateQuiz} className="space-y-6">
          {/* Topic Input */}
          <div>
            <label className="text-xs font-extrabold uppercase tracking-wider text-slate-500 dark:text-slate-400 block mb-2">
              Topic or Niche Prompt
            </label>
            <div className="relative">
              <input
                type="text"
                required
                maxLength={80}
                value={topicInput}
                onChange={e => setTopicInput(e.target.value)}
                placeholder="e.g. 90s Hip Hop, Quantum Physics, Greek Gods, Electric Cars..."
                className="w-full pl-4 pr-10 py-4 rounded-2xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm font-bold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-pink-500"
              />
              <Sparkles className="w-5 h-5 text-pink-500 absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>

          {/* Quick Suggestion Chips */}
          <div>
            <span className="text-[11px] font-extrabold uppercase tracking-wider text-slate-400 block mb-2">
              Trending Quick Topics
            </span>
            <div className="flex flex-wrap gap-2">
              {QUICK_TOPICS.map((topic, idx) => (
                <button
                  type="button"
                  key={idx}
                  onClick={() => setTopicInput(topic)}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800/80 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold text-xs transition-colors border border-slate-200/50 dark:border-slate-700/50"
                >
                  + {topic}
                </button>
              ))}
            </div>
          </div>

          {/* Options Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 border-t border-slate-100 dark:border-slate-800">
            {/* Difficulty Selector */}
            <div>
              <label className="text-xs font-extrabold uppercase tracking-wider text-slate-500 dark:text-slate-400 block mb-2">
                Difficulty Level
              </label>
              <div className="grid grid-cols-3 gap-2">
                {(['Easy', 'Medium', 'Hard'] as Difficulty[]).map(d => (
                  <button
                    type="button"
                    key={d}
                    onClick={() => setDifficulty(d)}
                    className={`py-2.5 rounded-xl font-extrabold text-xs transition-all ${
                      difficulty === d
                        ? 'bg-violet-600 text-white shadow-md'
                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200'
                    }`}
                  >
                    {d}
                  </button>
                ))}
              </div>
            </div>

            {/* Question Count Selector */}
            <div>
              <label className="text-xs font-extrabold uppercase tracking-wider text-slate-500 dark:text-slate-400 block mb-2">
                Number of Questions
              </label>
              <div className="grid grid-cols-2 gap-2">
                {[5, 10].map(cnt => (
                  <button
                    type="button"
                    key={cnt}
                    onClick={() => setQuestionCount(cnt)}
                    className={`py-2.5 rounded-xl font-extrabold text-xs transition-all ${
                      questionCount === cnt
                        ? 'bg-pink-600 text-white shadow-md'
                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200'
                    }`}
                  >
                    {cnt} Questions
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Error Message */}
          {errorMsg && (
            <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs font-bold flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{errorMsg}</span>
            </div>
          )}

          {/* Submit Action */}
          <button
            type="submit"
            disabled={isGenerating || !topicInput.trim()}
            className="w-full py-4 rounded-2xl font-black text-sm text-white shadow-xl bg-gradient-to-r from-violet-600 via-pink-600 to-rose-600 hover:opacity-95 flex items-center justify-center gap-2 transition-all hover:scale-[1.01] active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Crafting AI Trivia Questions...
              </>
            ) : (
              <>
                <Zap className="w-5 h-5" />
                Generate AI Quiz Now
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
